"""create tables

Revision ID: 108da83465ff
Revises: 484e6c955b82
Create Date: 2023-06-07 17:14:14.172807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '108da83465ff'
down_revision = '484e6c955b82'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
