"""Add star_rating column to categories table

Revision ID: 133fec5fd2f3
Revises: 4c03da255b74
Create Date: 2023-06-08 02:36:24.886260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '133fec5fd2f3'
down_revision = '4c03da255b74'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
