"""Add star_rating column to tasks table

Revision ID: 6fb6f08b5897
Revises: 133fec5fd2f3
Create Date: 2023-06-08 02:55:26.818831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fb6f08b5897'
down_revision = '133fec5fd2f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
