"""Create table tasks

Revision ID: 80d1c750cf12
Revises: 6fb6f08b5897
Create Date: 2023-06-08 18:29:41.244779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80d1c750cf12'
down_revision = '6fb6f08b5897'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
